
version: "3.8"
services:
  springboot-app:
    container_name: riskcalculation-app
    image: riskcalculation-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mydb
    image: mysql
    restart: always
    volumes:
      - dockerdbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  ui:
    container_name: myangularapp
    image: riskcalculatorui:latest
    ports:
      - "8089:4200"
    restart: always 
    depends_on:
      - springboot-app

volumes:
  dockerdbdata: