version: "3.8"
services:
  reactapp:
    container_name: reactapp
    image: shruti02/reactapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080"
    depends_on:
      - springboot-app

  springboot-app:
    container_name: springriskcalculator
    image: shruti02/springriskcalculator
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mydb
    image: mysql
    restart: always
    volumes:
      - dockerdbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
  
volumes:
  dockerdbdata::

